from pathlib import Path
import json
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Image, Table, TableStyle, KeepTogether
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics

ROOT = Path(__file__).resolve().parent
OUT = ROOT / 'IBM_Telco_Churn_EDA_Report.pdf'
summary = json.loads((ROOT/'results/summary.json').read_text(encoding='utf-8'))

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='CoverTitle', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=25, leading=31, alignment=TA_CENTER, textColor=colors.HexColor('#123B4A'), spaceAfter=18))
styles.add(ParagraphStyle(name='CoverSub', parent=styles['Normal'], fontName='Helvetica', fontSize=13, leading=19, alignment=TA_CENTER, textColor=colors.HexColor('#456A73'), spaceAfter=10))
styles.add(ParagraphStyle(name='Section', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=17, leading=22, textColor=colors.HexColor('#123B4A'), spaceBefore=12, spaceAfter=9))
styles.add(ParagraphStyle(name='Subsection', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=11.5, leading=15, textColor=colors.HexColor('#168575'), spaceBefore=8, spaceAfter=4))
styles.add(ParagraphStyle(name='Body2', parent=styles['BodyText'], fontName='Helvetica', fontSize=9.5, leading=14, spaceAfter=6, textColor=colors.HexColor('#263238')))
styles.add(ParagraphStyle(name='Small', parent=styles['BodyText'], fontName='Helvetica', fontSize=7.5, leading=10, textColor=colors.HexColor('#455A64')))
styles.add(ParagraphStyle(name='Callout', parent=styles['BodyText'], fontName='Helvetica-Bold', fontSize=10.5, leading=15, backColor=colors.HexColor('#E8F4F1'), borderColor=colors.HexColor('#77B8A6'), borderWidth=.5, borderPadding=7, spaceBefore=5, spaceAfter=8, textColor=colors.HexColor('#123B4A')))
styles.add(ParagraphStyle(name='TableCell', parent=styles['BodyText'], fontName='Helvetica', fontSize=7.3, leading=9, textColor=colors.HexColor('#263238'), spaceAfter=0))
styles.add(ParagraphStyle(name='TableHeader', parent=styles['BodyText'], fontName='Helvetica-Bold', fontSize=7.3, leading=9, textColor=colors.white, spaceAfter=0))

def p(text, style='Body2'):
    return Paragraph(text, styles[style])

def img(name, width=7.0*inch, height=None):
    path = ROOT/'figures'/name
    im = Image(str(path), width=width, height=height if height is not None else width*0.42)
    im.hAlign = 'CENTER'
    return im

def table(data, widths=None, font=8):
    wrapped = []
    for row_i, row in enumerate(data):
        wrapped.append([Paragraph(str(value), styles['TableHeader' if row_i == 0 else 'TableCell']) for value in row])
    t = Table(wrapped, colWidths=widths, repeatRows=1, hAlign='LEFT')
    t.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0),colors.HexColor('#123B4A')),('TEXTCOLOR',(0,0),(-1,0),colors.white),
        ('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTNAME',(0,1),(-1,-1),'Helvetica'),
        ('FONTSIZE',(0,0),(-1,-1),font),('LEADING',(0,0),(-1,-1),font+2),
        ('GRID',(0,0),(-1,-1),.25,colors.HexColor('#B0BEC5')),('VALIGN',(0,0),(-1,-1),'TOP'),
        ('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#F3F8F7')]),('LEFTPADDING',(0,0),(-1,-1),5),('RIGHTPADDING',(0,0),(-1,-1),5),
    ]))
    return t

def footer(canvas, doc):
    canvas.saveState(); canvas.setFont('Helvetica',7); canvas.setFillColor(colors.HexColor('#607D8B'))
    canvas.drawString(.65*inch,.38*inch,'IBM Exploratory Data Analysis for Machine Learning | yanyixuan')
    canvas.drawRightString(7.85*inch,.38*inch,f'{doc.page}')
    canvas.restoreState()

story=[]
story += [Spacer(1, .85*inch), p('Telecom Customer Churn', 'CoverTitle'), p('Exploratory Data Analysis, Feature Engineering, and Hypothesis Testing', 'CoverSub'), Spacer(1,.28*inch), p('Final Project Report', 'CoverSub'), Spacer(1,.55*inch), p('<b>Author</b>: yanyixuan', 'CoverSub'), p('<b>Dataset</b>: IBM Telco Customer Churn sample', 'CoverSub'), p('<b>Analysis date</b>: September 2026', 'CoverSub'), Spacer(1,.55*inch), p('Decision focus: identify customer segments where retention experiments are most likely to create measurable value.', 'Callout'), PageBreak()]
story += [p('Executive Summary','Section'), p('This project studies IBM\'s public Telco Customer Churn sample. The business question is which customer segments should receive retention attention first, and what evidence should guide a follow-up experiment. The analysis uses a discovery sample for EDA and a held-out confirmation sample for the three pre-specified hypotheses. This separation reduces the risk of presenting a relationship that was selected only after looking at the answer.'), p('The dataset contains 7,043 customers and 21 original columns. The overall churn rate is 26.5%. The main operational signal is contract type: in the confirmation sample, month-to-month customers churned at 43.7%, compared with 6.0% for one-year or two-year customers. The absolute difference was 37.7 percentage points, with a 95% confidence interval of 34.5 to 40.9 percentage points. The relationship remained significant after Bonferroni correction across the three planned tests.'), p('The results are associative. They support prioritizing a retention experiment, such as a contract-conversion offer or onboarding intervention, but they do not prove that changing contract type alone will cause lower churn. The next business step is a randomized or carefully matched experiment with cost, margin, customer experience, and eligibility constraints measured explicitly.', 'Callout'), p('Key results','Subsection'), table([['Metric','Result'],['Rows / original columns','7,043 / 21'],['Duplicate rows','0'],['Missing TotalCharges','11 rows (0.16%)'],['Churned customers','1,869 (26.5%)'],['Confirmation sample','2,113 customers, seed 42'],['Engineered model matrix','4,930 x 51 after train-only fitting']], [2.1*inch,4.9*inch], 8.5), PageBreak()]
story += [p('1. Data Summary','Section'), p('The IBM Telco Customer Churn dataset describes customer account structure, service subscriptions, billing preferences, tenure, monthly charges, total charges, and the binary churn outcome. The target is Churn, encoded as ChurnFlag = 1 for Yes and 0 for No. CustomerID is an identifier and is excluded from modeling.'), p('The source file was downloaded from IBM\'s archived public sample repository. The exact source URL and SHA-256 checksum are recorded in results/summary.json so the data version can be checked.'), table([['Variable group','Examples','Role in analysis'],['Customer profile','gender, SeniorCitizen, Partner, Dependents','Potential segment descriptors'],['Account and contract','Contract, PaperlessBilling, PaymentMethod','Primary business intervention candidates'],['Services','InternetService, TechSupport, OnlineSecurity, StreamingTV','Service mix and experience context'],['Numeric behavior','tenure, MonthlyCharges, TotalCharges','Distribution, association, and transformation'],['Outcome','Churn','Binary target']], [1.45*inch,2.3*inch,3.25*inch], 7.7), p('Data quality checks found no duplicate rows. TotalCharges contains 11 blank values, and each blank corresponds to tenure = 0, which is consistent with a newly started account. The analysis keeps these rows and handles the numeric missing values inside a train-only imputation pipeline.'), img('01_distributions.png'), p('Figure 1. Numeric distributions by churn status in the discovery sample.', 'Small'), PageBreak()]
story += [p('2. Exploration Plan','Section'), p('The analysis follows a decision-oriented sequence: first verify structure and data quality; then inspect outcome prevalence and numeric distributions; next compare churn across contract, payment, and service segments; finally examine whether combinations such as contract and tenure reveal a more actionable pattern. Hypotheses were specified before the held-out confirmation sample was tested.'), table([['Step','Question','Output'],['Structure and quality','What is present, missing, duplicated, or incorrectly typed?','Schema, missingness table, parsing checks'],['Outcome profile','How common is churn and how imbalanced is the target?','Churn rate and segment denominators'],['Segment EDA','Which account groups have visibly different rates?','Rate charts with 95% Wilson intervals'],['Relationship EDA','Do tenure and charges move with churn?','Distributions, boxplot, correlation heatmap'],['Confirmation','Could the planned differences be sampling noise?','Chi-square and Welch tests with correction'],['Preparation','Can the data enter a future model without leakage?','Train-only imputation, scaling, one-hot encoding']], [1.35*inch,3.25*inch,2.4*inch], 7.7), p('The analysis treats correlation as useful for prediction and prioritization, while keeping causal claims separate. A high churn rate in a group is a reason to test an intervention, not proof that the group characteristic causes churn.', 'Callout'), PageBreak()]
story += [p('3. EDA Findings','Section'), p('Contract type is the clearest segmentation signal. Discovery-sample churn rates were 42.3% for month-to-month, 12.0% for one-year, and 2.6% for two-year contracts. Payment method also separated customers: electronic check was 44.4%, while automatic credit card was 15.0%. These patterns should be read with their sample sizes and with the possibility that contract and payment choices reflect other customer differences.'), img('02_segments.png'), p('Figure 2. Churn rates and 95% Wilson intervals for the main contract and payment segments.', 'Small'), p('Tenure and contract interact. Month-to-month churn was 51.6% in the 0-12 month band and declined to 25.7% in the 49-72 month band. The heatmap shows why a one-variable summary is not enough: the risk profile changes with both the customer relationship stage and contract type.', 'Body2'), img('03_contract_tenure.png'), p('Figure 3. Contract and tenure combination in the discovery sample; labels include group counts.', 'Small'), PageBreak()]
story += [p('4. Cleaning and Feature Engineering','Section'), p('Cleaning decisions were documented before modeling. TotalCharges was parsed as numeric; blank values were retained and represented with a missingness indicator. The identifier CustomerID was removed from the feature matrix. No target-derived columns were included.'), p('The feature pipeline is fit only on the discovery/training partition and then applied to the confirmation partition. Numeric columns use median imputation followed by StandardScaler. Categorical columns use OneHotEncoder(handle_unknown="ignore"). Two binary indicators capture new customers and original missingness. Additional features include log-transformed tenure and total charges, plus a MonthlyCharges x NewCustomer interaction.'), p('The before-and-after evidence below shows the specific cleaning and encoding operations. The 11 blank TotalCharges values become finite model inputs through training-only median imputation, while the original missingness is preserved as TotalChargesMissing. The single Contract column becomes three binary one-hot columns, with exactly one active category in each row.'), img('06_cleaning_encoding_before_after.png', height=4.08*inch), p('Figure 4. Before-and-after evidence for missing values, one-hot encoding, and the model-ready pipeline.', 'Small'), PageBreak(), img('05_preprocessing_output.png'), p('Figure 5. Executed preprocessing output. The final matrix has 51 columns and contains finite numeric values.', 'Small'), img('04_charges_correlations.png'), p('Figure 6. Monthly charges by churn status and correlations among numeric variables.', 'Small'), PageBreak()]
story += [p('5. Hypotheses and Significance Tests','Section'), p('The confirmation sample contains 2,113 customers that were not used to choose the EDA story. The three tests below were planned around business questions. A family-wise alpha of 0.05 was controlled with the Bonferroni threshold 0.05 / 3 = 0.0167.'), table([['Hypothesis','Test','Result','Decision'],['H1: Month-to-month contract is associated with higher churn','2 x 2 Pearson chi-square','χ²=373.43, p<0.0001; risk difference 37.7 pp (95% CI 34.5-40.9); risk ratio 7.24','Reject H0 after correction'],['H2: Churners have higher monthly charges','Welch two-sample t-test','Mean difference $13.81 (95% CI $11.30-$16.32), p<0.0001','Reject H0 after correction'],['H3: Payment method is associated with churn','4 x 2 Pearson chi-square','χ²=220.71, p<0.0001; Cramer V=0.323','Reject H0 after correction']], [1.45*inch,1.55*inch,3.25*inch,1.15*inch], 7), p('H1 is the strongest operational result. The confirmation contingency table was: month-to-month 518 churned and 667 retained; longer-term contracts 56 churned and 872 retained. The minimum expected cell count was 252, so the chi-square approximation is well supported. Fisher\'s exact test also gave p < 0.0001.'), p('Interpretation: the evidence is strong that churn status and contract type are associated in this sample. The effect size is large enough to matter operationally, not merely statistically. A retention program could prioritize month-to-month customers, especially early-tenure customers, while measuring whether the offer causes incremental retention rather than simply selecting customers who were already more likely to stay.'), PageBreak()]
story += [p('6. Recommendations and Limitations','Section'), table([['Recommendation','Reason','Measurement'],['Prioritize month-to-month customers','Largest observed absolute and relative churn gap','Randomized offer acceptance, churn at 90/180 days, margin'],['Focus early-tenure onboarding','Month-to-month churn is highest in the first 12 months','Activation milestones, support contacts, conversion to longer contract'],['Investigate electronic-check experience','Highest payment-method churn rate in EDA','Payment friction, failed payments, switching behavior'],['Use a held-out or time-based validation sample','Reduces selection bias in analysis','Pre-register comparisons and report confidence intervals']], [1.6*inch,2.5*inch,3.3*inch], 7.5), p('Limitations include the observational design, possible confounding between contract choice and customer value, the cross-sectional nature of the sample, and the fact that statistical significance does not establish business profitability. Monthly charges are associated with churn, but the direction and mechanism require further study. Future modeling should use time-aware validation if timestamps become available, include calibration and class-imbalance checks, and evaluate expected retention profit rather than accuracy alone.'), p('Conclusion','Subsection'), p('The dataset is sufficiently clean and structured for a supervised churn workflow after documented preprocessing. The strongest insight is a large and reproducible churn gap by contract type, reinforced by early-tenure patterns. The appropriate next action is a controlled retention experiment with a clear success metric and a pre-specified analysis plan.'), p('Reproducibility','Subsection'), p('All figures, tables, cleaned outputs, engineered matrices, and code are included with this report. Run <font name="Courier">python analysis.py</font> from the project directory to regenerate the artifacts. The raw IBM sample is referenced by URL in the README and is not required to be committed to the repository.'), p('Source: IBM Telco Customer Churn sample, https://github.com/IBM/telco-customer-churn-on-icp4d/tree/master/data', 'Small')]

doc = SimpleDocTemplate(str(OUT), pagesize=letter, rightMargin=.65*inch, leftMargin=.65*inch, topMargin=.6*inch, bottomMargin=.62*inch, title='Telecom Customer Churn EDA Report', author='yanyixuan')
doc.build(story, onFirstPage=footer, onLaterPages=footer)
print(OUT)
